name: Node Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run lint

    - name: Run npm audit
      run: npm audit --audit-level=high

    - name: Install and Run Retire.js
      run: |
        npm install -g retire
        retire --json > retire-report.json
      continue-on-error: true

    - name: Install and Run OWASP Dependency-Check
      run: |
        wget https://github.com/jeremydmiller/dotnet-dep-check/releases/download/v6.1.4/dependency-check-6.1.4-release.zip
        unzip dependency-check-6.1.4-release.zip
        ./dependency-check/bin/dependency-check.sh --project "Node.js Project" --format "JSON" --out "dependency-check-report.json"
      continue-on-error: true

    - name: Install and Run Checkov
      run: |
        pip install checkov
        checkov -d . --json-file-path checkov-report.json
      continue-on-error: true

    - name: Install and Run Checkmate
      run: |
        npm install -g @checkmate/checkmate
        checkmate -r . --format json --output checkmate-report.json
      continue-on-error: true

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Check SARIF file
      run: |
        ls -l /home/runner/work/node_example/results
        cat /home/runner/work/node_example/results/javascript.sarif || echo "SARIF file not found"

