name: Node Project CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: write   # Allow access to repository content
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}  # Correct token usage

    - name: Verify repository access
      run: |
        echo "Testing repository access..."
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test

    - name: Verify npm audit access
      run: |
        echo "Testing npm audit..."
        npm audit --audit-level=high
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Run lint
      run: npm run lint

    - name: Dependency Review
      uses: github/dependency-review-action@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

