name: Node Project CI

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read
  issues: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    
    # Run unit tests
    - run: npm test
    
    # Run ESLint for linting
    - run: npm run lint

    # Run npm audit for security vulnerabilities in dependencies
    - name: Check for vulnerabilities
      run: npm audit --audit-level=high
    
    # Dependency Review action (use v3 instead of v2)
    - name: Dependency Review
      uses: github/dependency-review-action@v3
      with:
        fail-on-severity: high

  # CodeQL Analysis for multi-language static analysis
  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript  # Add more languages if your project supports them

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
