name: Node Project CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}  # Use GH_TOKEN secret here

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run lint

    - name: Run npm audit
      run: npm audit --audit-level=high
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass GH_TOKEN as an environment variable

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass GH_TOKEN as an environment variable

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass GH_TOKEN as an environment variable

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass GH_TOKEN as an environment variable


