name: Node Project CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: write  # Ensure security events write permission
  actions: read  # Ensure actions read permission


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN secret

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run lint

    - name: Run npm audit
      run: npm audit --audit-level=high
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GITHUB_TOKEN as an environment variable

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GITHUB_TOKEN as an environment variable

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GITHUB_TOKEN as an environment variable

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GITHUB_TOKEN as an environment variable

    - name: Check SARIF file
      run: |
        ls -l /home/runner/work/node_example/results
        cat /home/runner/work/node_example/results/javascript.sarif


