name: Node Project CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: write   # Allow access to repository content
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ GH_TOKEN }}  # Ensure proper token usage

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run lint

    - name: Check for vulnerabilities
      run: npm audit --audit-level=high

    - name: Dependency Review
      uses: github/dependency-review-action@v3
      with:
        token: ${{ GH_TOKEN }}  # Ensure token is used if needed

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
