name: Node Project CI

on:
  push:
    branches: [ main ]  # Replace with your default branch name
  pull_request:
    branches: [ main ]  # Replace with your default branch name
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: write
  actions: read
  code-scanning: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
    - run: npm run lint

    - name: Run npm audit
      run: npm audit --audit-level=high
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check SARIF file
      run: |
        ls -l /home/runner/work/node_example/results
        cat /home/runner/work/node_example/results/javascript.sarif || echo "SARIF file not found"
